#:schema https://mise.jdx.dev/schema/mise.json

[plugins]
	taplo = "https://github.com/Okeanos/asdf-taplo"

# See https://github.com/jdx/mise/blob/main/registry.toml for what is officially available
# Everything else is just declared as a reference to keep track of it.
[tools]
	editorconfig-checker = "3.4.1" # GitHub Actions sha256sum=8412b617d9f6ee9af78df8122f627470b2782e29a977ee147322a49bae16bde5
	gitleaks = "8.29.0"            # GitHub Actions sha256sum=39e07ad810336fd0ae80d0bd61c60d0521f628173e7583583b5df4a38738522c
	lychee = "0.21.0"
	markdownlint-cli2 = "0.18.1"
	shellcheck = "0.11.0"
	shfmt = "3.12.0"
	taplo = "0.10.0"               # GitHub Actions sha256sum=8fe196b894ccf9072f98d4e1013a180306e17d244830b03986ee5e8eabeb6156
	yamllint = "1.37.1"
